---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault
    spec:
      containers:
      - image: hashicorp/vault
        imagePullPolicy: IfNotPresent
        env:
          - name: VAULT_LOCAL_CONFIG
            value: |
              {
                "ui": true,
                "backend": {
                  "file": {
                    "path": "/vault/file"
                  }
                },
                "listener": {
                  "tcp": {
                    "address": "0.0.0.0:8200",
                    "tls_disable": 1
                  }
                },
                "default_lease_ttl": "168h",
                "max_lease_ttl": "720h"
              }
        name: vault
        ports:
          - containerPort: 8200
            name: vault
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        args: ["server"]
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vault
  name: vault
spec:
  ports:
  - name: vault
    port: 8200
    protocol: TCP
    targetPort: vault
  selector:
    app: vault
  type: ClusterIP
status:
  loadBalancer: {}
