injector:
    enabled: true
server:
    dataStorage:
        enabled: true
    standalone:
        config: |
            ui = true

            backend "file" {
                path = "/vault/file"
            }

            listener "tcp" {
                address = "[::]:8200"
                cluster_address = "[::]:8201"
                tls_disable = 1
            }
            default_lease_ttl = "168h"
            max_lease_ttl = "720h"